[package]
name = "fftemplates"
version = "0.1.2"
authors = ["boris"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.1.0"
clap = "2.33.0"
dirs = "2.0.1"
fs_extra = "1.1.0"
